EXPLAIN SELECT * FROM READERS WHERE FIRSTNAME = 'John';

CREATE INDEX TITLE ON BOOKS (TITLE);

CREATE INDEX FIRSTNAME_AND_LASTNAME ON READERS (FIRSTNAME, LASTNAME);

EXPLAIN SELECT * FROM READERS WHERE FIRSTNAME = 'John';